### PR TITLE
Update taiga-hook.php

### PR DESCRIPTION
**Pull request by zxp86021**
fix getallheaders function won't get currect header value cause signature_verified function always return false

### CODE REVIEW

**Comment by mikeroneer** [comment]
hi @zxp86021 , thanks for supporting taigagram! For me it's still working with getallheaders(). What do you exactly think what's the problem there?

**Comment by zxp86021** [comment]
hi @mikeroneer , thank you for create such great service.
my problem is when we use offical taigagram bot, we always get wrong authentication message in taiga webhook setting.
photo_2016-12-05_10-55-59

so we clone this repo and test on our own VPS (ubuntu 16.04 + nginx + php7.0.8), we found $headers["X-Taiga-Webhook-Signature"] value is empty, that cause signature_verified function always return false, and this problem solved after use $_SERVER

**Comment by mikeroneer** [comment]
hi @zxp86021,
regarding to the official taiga documentation, the header is named like mentioned. Nevertheless, if the issue occurs, I will have a look at it!

**Review by mikeroneer — APPROVED** [review]
thanks for the contribution

**Pull request merged**
